package com.shangwj.blog.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..Menu.id
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..Menu.name
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..Menu.parentId
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..Menu.id
     *
     * @return the value of test..Menu.id
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..Menu.id
     *
     * @param id the value for test..Menu.id
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..Menu.name
     *
     * @return the value of test..Menu.name
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..Menu.name
     *
     * @param name the value for test..Menu.name
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..Menu.parentId
     *
     * @return the value of test..Menu.parentId
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..Menu.parentId
     *
     * @param parentid the value for test..Menu.parentId
     *
     * @mbggenerated Wed Aug 07 22:47:36 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}